pollenflug_gefahrenindex:
  url: "https://opendata.dwd.de/climate_environment/health/alerts/s31fg.json"
  db_infos:
    db: "dwd"
    datalake: "datalake"
    information_layer: "information_layer"
git_root: ""
env:
  _EXECUTION_ENVIRONMENT_: ""
  _ENVIRONMENT_: ""
  _EXECUTION_MODE_: ""
  _DBINSTANCE_INACTIVITY_TTL_: "5s"
runs_on_ga: ""
