pollenvorhersage:
  url: "gAAAAABn4buymTqBJIWGHgzVJkizGkmO5cmA7zfxjKAcVGUfbegHIt-oWByQ15aN16rfKtXB7eE1vX8b0Rq6Vd16f-JI78astvL7kd9pkmrkeoOZ3y6n3DyPicew1t0aBi8or49G7vO2cE4NAJEvry3qLKa-E13jSg=="
  plz:
   - "gAAAAABn4chMXnHJbTgHvP8UcSP3E788qtViciL9yYOMIg2EcZ4ssWtqXQYjuCEuZDVVOkhKR5MHcZhCA5N7jOHa6hGW1n1u2w=="
   - "gAAAAABn6HlctCli5eRcje55dRtnylfOjzgWftAOlSLQQ_v3w2uLZSNl4fzkhdaVt2AT25S4d-ktC6MtxwNtiJ-bxy7Obtb7oQ=="
   - 'gAAAAABn9Ye--qwYS1YUeo1Hg9atAtlF79i3RTsgJZK0vgc2VA1MW2LDVCekdIqAiozeh7NsGHnbjzFF4PYzuf5sOmdTFRIzhA=='
   - 'gAAAAABn9YgaiO9lQlao02t06_ynIaN4y5BUk5QzbDHG-0ojc85-mLCtDJTOQ95gmUfK2CO3u1Lx79299_wdd5YTLyi5CG407Q=='
   - 'gAAAAABn9Yhf5TyJ8mJdbl-C_DXu1gzBHwtAmMwFYz6Gwk_T2FCSMmfZ41cjtxC13geEhmTqjqPGrCzk8ZCNsGX7vfT2Aceikw=='
   - 'gAAAAABn9YijCQDKH56rEldpE7nCZEZ_rbu1bj0Dv7vbQVHb-ll7GzeLxg-Mu61ldGXdd_jTwSOrDNvj97eomSsEBElCrWgZ7A=='
   - 'gAAAAABn9fQkVHk7EA-JtvhHgQNZg674_kXWMgqRZbsHFKDElWznvIPtybUC_oojsv9VPFZH6xWnh8yJtno6pWrlmkvYPC62GQ=='
   - 'gAAAAABn9YlKRePHaOmYZACXIYqOJfFUsxvKXBKwUhSDbkzd60tU98vYNVKLg9xK3wc2ThhnmUjm3aC6TDclM3mYFgvPfRP0cA=='
   - 'gAAAAABn9YnjgDptIxxQWYsuDzYZw6p57cV0ro1uZh7QwmuBOhJbWvknOTGQ8Aema0QR9njwyhnesK-OKGKew4C5gX6f2-dNUg=='
   - 'gAAAAABn9YqEOBOT5vSHIxrn6KrBNfczZ5bAqO9aLO-O-ZWZMNK4zE7CGgwTT3Akhx475xXuPYbpwanfuAWsinW0EteZCHC5JA=='
  db_infos:
    db: "pollenvorhersage"
    datalake:
      name: "datalake"
      tables:
        webpages:
          name: webpages
          path: ""
          primary_key:
            - file
            - last_modified_date
    information_layer:
      name: "information_layer"
      tables:
        pollenflug_vorhersage:
          name: pollenflug_vorhersage
          path: ""
          primary_key:
            - last_update_dt
            - plz
            - pollenart
            - date
git_root: ""
env:
  _EXECUTION_ENVIRONMENT_: ""
  _EXECUTION_MODE_: ""
runs_on_ga: ""
