name: ruff

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
 run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest release
        uses: EED-Solutions/eed_gha_workflows/.github/actions/ruff@Update-versions-of-actions
