name: ruff

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv # https://eed-solutions.atlassian.net/wiki/spaces/ES/pages/782434388/Best+Practice+uv+package+management#Github-Actions
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: set up ruff
        uses: astral-sh/ruff-action@v3
      - name: Run Ruff
        run: uv run ruff check --output-format=github
