name: Run Scripts on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest release tag
        id: get-latest-release
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=tag::$latest_tag"
      - name: Checkout latest release
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get-latest-release.outputs.tag }}
      - name: Install uv # https://eed-solutions.atlassian.net/wiki/spaces/ES/pages/782434388/Best+Practice+uv+package+management#Github-Actions
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run script
        env:
          MD_TOKEN: ${{ secrets.MD_TOKEN }}
        run: |
          uv run src/eed_webscrapping_scripts/create_views
