name: Create views on release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: get current branch
        id: get-current-branch
        run: |
          branch=$(git branch --show-current) && echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "branch=$branch"
      - name: Install uv # https://eed-solutions.atlassian.net/wiki/spaces/ES/pages/782434388/Best+Practice+uv+package+management#Github-Actions
        if: ${{ steps.get-current-branch.outputs.branch == 'main'}}
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Setup Python
        if: ${{ steps.get-current-branch.outputs.branch == 'main'}}
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install dependencies
        if: ${{ steps.get-current-branch.outputs.branch == 'main'}}
        run: |
          python -m pip install --upgrade pip
          uv sync
      - name: Run script
        if: ${{ steps.get-current-branch.outputs.branch == 'main'}}
        env:
          MD_TOKEN: ${{ secrets.MD_TOKEN }}
        run: |
          uv run --python $(cat .python-version) src/eed_webscrapping_scripts/dwd/create_views.py
