name: Run Scripts on Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  run:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Get latest release tag
        id: get-latest-release
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1 --branches main)) && echo "{name}={$latest_tag}" >> $GITHUB_OUTPUT
      - name: Checkout latest release
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-latest-release.outputs.tag }}
      - name: Install uv # https://eed-solutions.atlassian.net/wiki/spaces/ES/pages/782434388/Best+Practice+uv+package+management#Github-Actions
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          uv sync
      - name: Run script
        env:
          MD_TOKEN: ${{ secrets.MD_TOKEN }}
        run: |
          uv run --python $(cat .python-version) src/eed_webscrapping_scripts/dwd/create_views.py
