name: Create views on release

permissions:
  contents: read

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: EED-Solutions/eed_gha_workflows/.github/actions/checkout_code@main
      - name: get current branch
        id: get-current-branch
        run: |
          branch=$(git branch --show-current) && echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "branch=$branch"
      - name: Install uv # https://eed-solutions.atlassian.net/wiki/spaces/ES/pages/782434388/Best+Practice+uv+package+management#Github-Actions
        if: ${{ steps.get-current-branch.outputs.branch == 'main'}}
        uses:  EED-Solutions/eed_gha_workflows/.github/actions/install_uv@main
        with:
          version-file: .python-version
      - name: Install dependencies
        if: ${{ steps.get-current-branch.outputs.branch == 'main'}}
        uses: EED-Solutions/eed_gha_workflows/.github/actions/set_up_py_env@main
      - name: Run script
        if: ${{ steps.get-current-branch.outputs.branch == 'main'}}
        env:
          MD_TOKEN: ${{ secrets.MD_TOKEN }}
        run: |
          uv run --python $(cat .python-version) src/eed_webscrapping_scripts/dwd/create_views.py
