name: daily scrapping

on:
  schedule:
    - cron: 0 14 * * *
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: opt-nc/setup-duckdb-action@v1.0.8
        with:
          version: v1.2.0
      - name: Get latest release tag
        id: get-latest-release
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1 --branches main) --abbrev=0)
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT
          echo $latest_tag
      - name: Checkout latest release
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-latest-release.outputs.tag }}
      - name: Install uv # https://eed-solutions.atlassian.net/wiki/spaces/ES/pages/782434388/Best+Practice+uv+package+management#Github-Actions
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          uv sync
      - name: Run script
        env:
          MD_TOKEN: ${{ secrets.MD_TOKEN }}
          RUNS_ON_GA: ${{ vars.RUNS_ON_GA }}
          _ENVIRONMENT_: ${{ vars._ENVIRONMENT_ }}
        run: |
          runs_on_ga=$(uvx python -c "import os; print(os.getenv('RUNS_ON_GA'))")
          _environment_=$(uvx python -c "import os; print(os.getenv('_ENVIRONMENT_'))")
          echo $runs_on_ga
          echo $_environment_
          uv run src/eed_webscrapping_scripts/main.py
