on:
  schedule:
    - cron: 0 14 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Run script
        env:
          MD_TOKEN: ${{ secrets.MD_TOKEN }}
        run: |
          uv run --python 3.11 src\eed_webscrapping_scripts\main.py
