name: pytests

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
 run:
    runs-on: ubuntu-latest
    steps:
      - name: run pytests
        uses: EED-Solutions/eed_gha_workflows/.github/actions/pytests@Update-versions-of-actions
        with:
          encryption_password: ${{ secrets.ENCRYPTION_PASWORD }}
          encryption_result: ${{ secrets.ENCRYPTION_RESULT }}
          encryption_salt: ${{ secrets.ENCRYPTION_SALT }}
