on:
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install uv # https://eed-solutions.atlassian.net/wiki/spaces/ES/pages/782434388/Best+Practice+uv+package+management#Github-Actions
          uses: astral-sh/setup-uv@v4
          with:
            enable-cache: true
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version-file: .python-version
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            uv sync
        - name: Run pytests
          run: |
            echo "tbd"
